# Generated by Django 4.0 on 2022-01-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperAdmin',
        ),
    ]
