# Generated by Django 2.1 on 2020-01-08 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('ratings', models.FloatField(default=0, max_length=1, null=True)),
                ('location', models.TextField(max_length=600, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6, null=True)),
                ('DOB', models.DateField(default=django.utils.timezone.now, null=True)),
                ('DOR', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
