# Generated by Django 2.1 on 2020-01-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_auto_20200108_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='University',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='council',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fathers_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualified_year',
            field=models.FloatField(max_length=4, null=True),
        ),
    ]
