# Generated by Django 2.1 on 2020-01-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_auto_20200108_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.FileField(max_length=300, null=True, upload_to='Doctors/'),
        ),
    ]
