# Generated by Django 4.0 on 2022-01-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0008_additionalinfo_rename_university_doctor_university_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='additional_qualifications',
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Services.doctor'),
        ),
    ]
