# Generated by Django 4.0 on 2022-01-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0009_remove_doctor_additional_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(max_length=300, upload_to='Doctors/'),
        ),
    ]
