# Generated by Django 4.0 on 2022-01-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0010_alter_doctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='ratings',
        ),
    ]
