# Generated by Django 2.1 on 2020-01-01 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_auto_20191230_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
