# Generated by Django 2.1 on 2020-01-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_auto_20200101_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
    ]
