# Generated by Django 2.1 on 2020-01-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reporter', models.CharField(max_length=255)),
                ('complaint', models.CharField(max_length=350)),
                ('date', models.CharField(max_length=50)),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('feedback', models.CharField(max_length=350)),
                ('ratings', models.FloatField(max_length=1)),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
    ]
