# Generated by Django 4.0 on 2022-02-02 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField(default='111111')),
                ('complaint', models.CharField(max_length=300)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2022, 2, 2, 23, 6, 44, 780662))),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField(default='111111')),
                ('feedback', models.CharField(max_length=300)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2022, 2, 2, 23, 6, 44, 780662))),
            ],
        ),
    ]
