# Generated by Django 4.0 on 2022-02-02 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_complaint_datetime_alter_feedback_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 23, 7, 26, 3693)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='doctor_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 23, 7, 26, 3693)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='doctor_id',
            field=models.IntegerField(),
        ),
    ]
