# Generated by Django 2.1 on 2020-01-02 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20191230_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
