# Generated by Django 2.1 on 2020-01-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200102_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(max_length=350),
        ),
    ]
