# Generated by Django 4.0.3 on 2022-03-12 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_complaint_datetime_alter_complaint_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 18, 28, 52, 580429)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 18, 28, 52, 580429)),
        ),
    ]
