# Generated by Django 4.0 on 2022-01-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rules', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
